### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by genericness** [daijro/SearchifyX#10]
Hey!

Would it be possible for you to release the account creator for Quora Poe as it's own python file, so it could be used seperately?

Might be out of scope for this project but it's a very useful tool and would be great to implement in other projects, using Poe as a ChatGPT API.

**Comment by daijro** [comment]
Done! Released as [poegen.py](https://github.com/daijro/SearchifyX/blob/main/poegen.py). I've added instructions at the top of the file.
