### ISSUE TITLE
Bing has stopped working, again

### ISSUE THREAD

**Issue by Plurmo** [daijro/SearchifyX#5]
This issue has happened before, so it should be a relatively easy fix 👍

**Comment by daijro** [comment]
Hello, I can't seem to reproduce this error.
Are you able to visit Bing in a browser? Is there a captcha blocking it?

Thanks! 😁

**Comment by Plurmo** [comment]
Yes, I'm able to visit bing without any captcha. I also asked two other friends for their input and bing still didn't work, while google and startpage still working as intended.

We have tried v1.1 portable and installer versions.
We have tried Windows 10 and Windows 11.

**Comment by daijro** [comment]
Hello! Sorry for the extremely late response; I've taken a break from GitHub to focus on schoolwork.

I believe the scraper needs a complete overhaul. I had saved a few ideas for this project: the scraping system needs to be rewritten to be modular, so a new release doesn't have to drop each time a website breaks. I also had plans to add many more search engine options and fix several optimization issues.

Unfortunately, I was forced to stop my work to focus on studying. In my next break, I hope to maintain this project again and hopefully make it much more future-proof.

Thanks for your patience.

**Comment by daijro** [comment]
Hello, I have fixed the scraper. It should be much faster and return higher quality results now.

Feel free to let me know if you still have any troubles with it. I am thinking about working on a major update over the upcoming break: adding ChatGPT, built in web browser, etc. Thanks!
